export interface CourseData {
  id: string;
  course_code: string;
  course_name: string;
  course_units: string;
  course_description: string;
  prerequisites: string;
}

export const courseDatabase: CourseData[] = [
  // Computer Science
  {
    id: "1",
    course_code: "CSE 8A",
    course_name: "Introduction to Computer Science: Java (I)",
    course_units: "4",
    course_description: "Introduction to computer programming in Java. Covers fundamental programming concepts including variables, control structures, methods, and arrays.",
    prerequisites: "None",
  },
  {
    id: "2",
    course_code: "CSE 8B",
    course_name: "Introduction to Computer Science: Java (II)",
    course_units: "4",
    course_description: "Continuation of CSE 8A. Covers object-oriented programming, inheritance, polymorphism, and basic data structures.",
    prerequisites: "CSE 8A",
  },
  {
    id: "3",
    course_code: "CSE 12",
    course_name: "Basic Data Structures and Object-Oriented Design",
    course_units: "4",
    course_description: "Implementation of basic data structures and object-oriented design principles.",
    prerequisites: "CSE 8B or CSE 11",
  },
  {
    id: "4",
    course_code: "CSE 15L",
    course_name: "Software Tools and Techniques Laboratory",
    course_units: "2",
    course_description: "Hands-on experience with software development tools and techniques.",
    prerequisites: "CSE 8B or CSE 11",
  },
  {
    id: "5",
    course_code: "CSE 20",
    course_name: "Discrete Mathematics",
    course_units: "4",
    course_description: "Mathematical foundations for computer science including logic, sets, and combinatorics.",
    prerequisites: "MATH 20A",
  },
  {
    id: "6",
    course_code: "CSE 21",
    course_name: "Mathematics for Algorithms and Systems",
    course_units: "4",
    course_description: "Mathematical concepts essential for algorithm analysis and system design.",
    prerequisites: "CSE 20, MATH 20B",
  },
  {
    id: "7",
    course_code: "CSE 30",
    course_name: "Programming and Data Structures",
    course_units: "4",
    course_description: "Advanced programming concepts and data structures implementation.",
    prerequisites: "CSE 12",
  },
  {
    id: "8",
    course_code: "CSE 100",
    course_name: "Advanced Data Structures",
    course_units: "4",
    course_description: "Advanced data structures including trees, graphs, and algorithm analysis.",
    prerequisites: "CSE 12, CSE 21",
  },
  {
    id: "9",
    course_code: "CSE 101",
    course_name: "Design and Analysis of Algorithms",
    course_units: "4",
    course_description: "Design and analysis of efficient algorithms including dynamic programming, graph algorithms, and complexity theory.",
    prerequisites: "CSE 100, CSE 21",
  },
  {
    id: "10",
    course_code: "CSE 110",
    course_name: "Software Engineering",
    course_units: "4",
    course_description: "Software development methodologies, design patterns, and project management.",
    prerequisites: "CSE 100",
  },

  // Mathematics
  {
    id: "11",
    course_code: "MATH 20A",
    course_name: "Calculus for Science and Engineering",
    course_units: "4",
    course_description: "Differential calculus of functions of one variable. Applications to science and engineering.",
    prerequisites: "MATH 4C or MATH 10A or MATH 20A",
  },
  {
    id: "12",
    course_code: "MATH 20B",
    course_name: "Calculus for Science and Engineering",
    course_units: "4",
    course_description: "Integral calculus of functions of one variable. Applications to science and engineering.",
    prerequisites: "MATH 20A",
  },
  {
    id: "13",
    course_code: "MATH 20C",
    course_name: "Calculus and Analytic Geometry",
    course_units: "4",
    course_description: "Multivariable calculus including partial derivatives, multiple integrals, and vector calculus.",
    prerequisites: "MATH 20B",
  },
  {
    id: "14",
    course_code: "MATH 18",
    course_name: "Linear Algebra",
    course_units: "4",
    course_description: "Linear algebra including matrices, vector spaces, eigenvalues, and applications.",
    prerequisites: "MATH 20B",
  },
  {
    id: "15",
    course_code: "MATH 180A",
    course_name: "Introduction to Probability",
    course_units: "4",
    course_description: "Introduction to probability theory including random variables, distributions, and basic probability concepts.",
    prerequisites: "MATH 20C",
  },
  {
    id: "16",
    course_code: "MATH 180B",
    course_name: "Introduction to Mathematical Statistics",
    course_units: "4",
    course_description: "Mathematical statistics including estimation, hypothesis testing, and statistical inference.",
    prerequisites: "MATH 180A",
  },
  {
    id: "17",
    course_code: "MATH 181A",
    course_name: "Mathematical Statistics I",
    course_units: "4",
    course_description: "Advanced statistical theory including maximum likelihood estimation and hypothesis testing.",
    prerequisites: "MATH 180B",
  },

  // Economics
  {
    id: "18",
    course_code: "ECON 1",
    course_name: "Principles of Microeconomics",
    course_units: "4",
    course_description: "Introduction to microeconomic principles including supply and demand, market structures, and consumer behavior.",
    prerequisites: "None",
  },
  {
    id: "19",
    course_code: "ECON 2",
    course_name: "Principles of Macroeconomics",
    course_units: "4",
    course_description: "Introduction to macroeconomic principles including GDP, inflation, unemployment, and fiscal policy.",
    prerequisites: "ECON 1",
  },
  {
    id: "20",
    course_code: "ECON 3",
    course_name: "Intermediate Microeconomics",
    course_units: "4",
    course_description: "Advanced microeconomic theory including consumer choice, production theory, and market equilibrium.",
    prerequisites: "ECON 1, MATH 20A",
  },
  {
    id: "21",
    course_code: "ECON 4",
    course_name: "Intermediate Macroeconomics",
    course_units: "4",
    course_description: "Advanced macroeconomic theory including economic growth, business cycles, and monetary policy.",
    prerequisites: "ECON 2, MATH 20A",
  },
  {
    id: "22",
    course_code: "ECON 100A",
    course_name: "Microeconomic Analysis",
    course_units: "4",
    course_description: "Upper-division microeconomic analysis with mathematical rigor and advanced applications.",
    prerequisites: "ECON 3, MATH 20B",
  },
  {
    id: "23",
    course_code: "ECON 109",
    course_name: "Game Theory",
    course_units: "4",
    course_description: "Introduction to game theory including strategic interactions, Nash equilibrium, and applications to economics.",
    prerequisites: "ECON 3, MATH 20A",
  },
  {
    id: "24",
    course_code: "ECON 120A",
    course_name: "Econometrics",
    course_units: "4",
    course_description: "Introduction to econometrics including regression analysis, statistical inference, and economic modeling.",
    prerequisites: "ECON 3, MATH 20B",
  },

  // Chemistry
  {
    id: "25",
    course_code: "CHEM 6A",
    course_name: "General Chemistry I",
    course_units: "4",
    course_description: "Fundamental principles of chemistry including atomic structure, bonding, and chemical reactions.",
    prerequisites: "MATH 3C or MATH 4C or MATH 10A",
  },
  {
    id: "26",
    course_code: "CHEM 6B",
    course_name: "General Chemistry II",
    course_units: "4",
    course_description: "Continuation of CHEM 6A. Covers thermodynamics, kinetics, and equilibrium.",
    prerequisites: "CHEM 6A",
  },
  {
    id: "27",
    course_code: "CHEM 6C",
    course_name: "General Chemistry III",
    course_units: "4",
    course_description: "Continuation of CHEM 6B. Covers electrochemistry, nuclear chemistry, and coordination chemistry.",
    prerequisites: "CHEM 6B",
  },

  // Physics
  {
    id: "28",
    course_code: "PHYS 2A",
    course_name: "Physics-Mechanics",
    course_units: "4",
    course_description: "Classical mechanics including kinematics, dynamics, energy, momentum, and rotational motion.",
    prerequisites: "MATH 20A",
  },
  {
    id: "29",
    course_code: "PHYS 2B",
    course_name: "Physics-Electricity and Magnetism",
    course_units: "4",
    course_description: "Electricity and magnetism including electric fields, magnetic fields, and electromagnetic waves.",
    prerequisites: "PHYS 2A, MATH 20B",
  },
  {
    id: "30",
    course_code: "PHYS 2C",
    course_name: "Physics-Waves, Optics, and Modern Physics",
    course_units: "4",
    course_description: "Waves, optics, and modern physics including wave phenomena, geometric optics, and quantum mechanics.",
    prerequisites: "PHYS 2B, MATH 20C",
  },

  // Biology
  {
    id: "31",
    course_code: "BILD 1",
    course_name: "The Cell",
    course_units: "4",
    course_description: "Introduction to cell biology including cell structure, function, and molecular biology.",
    prerequisites: "None",
  },
  {
    id: "32",
    course_code: "BILD 2",
    course_name: "Multicellular Life",
    course_units: "4",
    course_description: "Introduction to organismal biology including genetics, evolution, and ecology.",
    prerequisites: "BILD 1",
  },
  {
    id: "33",
    course_code: "BILD 3",
    course_name: "Organismic and Evolutionary Biology",
    course_units: "4",
    course_description: "Organismic and evolutionary biology including biodiversity, adaptation, and evolutionary processes.",
    prerequisites: "BILD 2",
  },

  // Psychology
  {
    id: "34",
    course_code: "PSYC 1",
    course_name: "Introduction to Psychology",
    course_units: "4",
    course_description: "Introduction to psychology including cognitive processes, social behavior, and psychological research methods.",
    prerequisites: "None",
  },
  {
    id: "35",
    course_code: "PSYC 2",
    course_name: "Introduction to Psychology",
    course_units: "4",
    course_description: "Continuation of PSYC 1. Covers developmental psychology, personality, and psychological disorders.",
    prerequisites: "PSYC 1",
  },
  {
    id: "36",
    course_code: "PSYC 60",
    course_name: "Introduction to Statistics",
    course_units: "4",
    course_description: "Introduction to statistical methods in psychology including probability, hypothesis testing, and data analysis.",
    prerequisites: "MATH 20A",
  },

  // Cognitive Science
  {
    id: "37",
    course_code: "COGS 1",
    course_name: "Introduction to Cognitive Science",
    course_units: "4",
    course_description: "Introduction to cognitive science including perception, memory, language, and artificial intelligence.",
    prerequisites: "None",
  },
  {
    id: "38",
    course_code: "COGS 10",
    course_name: "Cognitive Consequences of Technology",
    course_units: "4",
    course_description: "Examination of how technology affects human cognition and behavior.",
    prerequisites: "None",
  },
  {
    id: "39",
    course_code: "COGS 14A",
    course_name: "Introduction to Statistical Analysis",
    course_units: "4",
    course_description: "Introduction to statistical analysis for cognitive science including probability, inference, and experimental design.",
    prerequisites: "MATH 20A",
  },

  // Data Science
  {
    id: "40",
    course_code: "DSC 10",
    course_name: "Principles of Data Science",
    course_units: "4",
    course_description: "Introduction to data science including data manipulation, visualization, and basic machine learning concepts.",
    prerequisites: "MATH 20A",
  },
  {
    id: "41",
    course_code: "DSC 20",
    course_name: "Programming for Data Science",
    course_units: "4",
    course_description: "Programming fundamentals for data science including Python, data structures, and algorithms.",
    prerequisites: "DSC 10",
  },
  {
    id: "42",
    course_code: "DSC 30",
    course_name: "Data Structures and Algorithms for Data Science",
    course_units: "4",
    course_description: "Data structures and algorithms specifically for data science applications.",
    prerequisites: "DSC 20",
  },
  {
    id: "43",
    course_code: "DSC 40A",
    course_name: "Theoretical Foundations of Data Science I",
    course_units: "4",
    course_description: "Mathematical foundations of data science including linear algebra, probability, and optimization.",
    prerequisites: "MATH 20C, DSC 20",
  },
  {
    id: "44",
    course_code: "DSC 80",
    course_name: "The Practice and Application of Data Science",
    course_units: "4",
    course_description: "Practical applications of data science including real-world projects and data analysis workflows.",
    prerequisites: "DSC 40A, DSC 30",
  },

  // Statistics
  {
    id: "45",
    course_code: "STAT 10",
    course_name: "Statistical Reasoning",
    course_units: "4",
    course_description: "Introduction to statistical reasoning including data analysis, probability, and statistical inference.",
    prerequisites: "MATH 20A",
  },
  {
    id: "46",
    course_code: "STAT 20",
    course_name: "Statistical Methods",
    course_units: "4",
    course_description: "Statistical methods including regression analysis, experimental design, and statistical computing.",
    prerequisites: "STAT 10",
  },
  {
    id: "47",
    course_code: "STAT 100A",
    course_name: "Introduction to Probability",
    course_units: "4",
    course_description: "Introduction to probability theory including random variables, distributions, and probability models.",
    prerequisites: "MATH 20C",
  },
  {
    id: "48",
    course_code: "STAT 100B",
    course_name: "Introduction to Mathematical Statistics",
    course_units: "4",
    course_description: "Mathematical statistics including estimation, hypothesis testing, and statistical inference.",
    prerequisites: "STAT 100A",
  },
  {
    id: "49",
    course_code: "STAT 101A",
    course_name: "Applied Statistical Methods",
    course_units: "4",
    course_description: "Applied statistical methods including regression, analysis of variance, and statistical modeling.",
    prerequisites: "STAT 20",
  },
  {
    id: "50",
    course_code: "STAT 101B",
    course_name: "Applied Statistical Methods",
    course_units: "4",
    course_description: "Advanced applied statistical methods including multivariate analysis and statistical computing.",
    prerequisites: "STAT 101A",
  },
];
